# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/main.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('config/config.template.json', 'config'),
        ('src/core/*.py', 'core'),
        ('src/providers/*.py', 'providers'),
        ('src/providers/transcription/*.py', 'providers/transcription'),
        ('src/providers/llm/*.py', 'providers/llm'),
        ('src/ui/*.py', 'ui'),
    ],
    hiddenimports=[
        'core',
        'core.config_manager',
        'core.audio_recorder',
        'core.hotkey_manager',
        'core.text_processor',
        'providers',
        'providers.transcription',
        'providers.transcription.base',
        'providers.transcription.groq_whisper',
        'providers.transcription.openai_whisper',
        'providers.transcription.deepgram',
        'providers.llm',
        'providers.llm.base',
        'providers.llm.ollama',
        'providers.llm.openai_llm',
        'providers.llm.groq_llm',
        'ui',
        'ui.system_tray',
        'ui.settings_window',
        'pystray._win32',
        'PIL._tkinter_finder',
        'sounddevice',
        'scipy',
        'scipy.io',
        'scipy.io.wavfile',
        'numpy',
        'keyboard',
        'pynput',
        'pyperclip',
        'pyautogui',
        'requests',
        'win32crypt',
        'win32api',
        'win32con',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'pandas',
        'notebook',
        'IPython',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='VoiceDictation',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Set to False for no console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,  # Add icon path if you have one
)
